import Mathlib.Algebra.MonoidAlgebra.Ideal

variable {A R k : Type*}

section

variable [Semiring R] [AddMonoid A]

/- An ideal is monomial if, for each ideal element, its coefficient-one
monomial terms are also contained in the ideal. -/
def Ideal.IsMonomial (I : Ideal (AddMonoidAlgebra R A)) : Prop :=
  ∀ f ∈ I, ∀ a ∈ f.coeff.support, AddMonoidAlgebra.of' R A a ∈ I

/-- An ideal is monomial if and only if it is generated by monomials. -/
lemma Ideal.IsMonomial.iff_exists (I : Ideal (AddMonoidAlgebra R A)) :
    I.IsMonomial ↔ ∃ s : Set A, I = Ideal.span (AddMonoidAlgebra.of' R A '' s) := by
  constructor
  · intro hI
    refine ⟨{a | AddMonoidAlgebra.of' R A a ∈ I}, le_antisymm ?_ ?_⟩
    · intro f hf
      rw [AddMonoidAlgebra.mem_ideal_span_of'_image]
      intro a ha
      exact ⟨a, hI f hf a ha, 0, by simp⟩
    · rw [Ideal.span_le]
      rintro _ ⟨a, ha, rfl⟩
      exact ha
  · rintro ⟨s, rfl⟩
    intro f hf a ha
    obtain ⟨b, hb, d, rfl⟩ := AddMonoidAlgebra.mem_ideal_span_of'_image.mp hf a ha
    simpa using Ideal.mul_mem_left (Ideal.span (AddMonoidAlgebra.of' R A '' s))
      (AddMonoidAlgebra.of' R A d) (Ideal.subset_span ⟨b, hb, rfl⟩)

/- The ideal generated by a set of monomials is a monomial ideal. -/
lemma Ideal.isMonomial_span_of'_image (s : Set A) :
    IsMonomial (Ideal.span (AddMonoidAlgebra.of' R A '' s) : Ideal (AddMonoidAlgebra R A)) :=
  (Ideal.IsMonomial.iff_exists _).mpr ⟨s, rfl⟩

/-- This is similar to the forward direction of `Ideal.IsMonomial.mem_iff`,
but does not require `a ∈ f.coeff.support` to apply it. -/
lemma Ideal.IsMonomial.single_mem {I : Ideal (AddMonoidAlgebra R A)} (hI : I.IsMonomial)
    {f : AddMonoidAlgebra R A} (hf : f ∈ I) (a : A) :
    AddMonoidAlgebra.single a (f.coeff a) ∈ I := by
  by_cases ha : a ∈ f.coeff.support
  · simpa [AddMonoidAlgebra.of'_apply] using
      Ideal.mul_mem_left I (AddMonoidAlgebra.single 0 (f.coeff a)) (hI f hf a ha)
  · rw [Finsupp.notMem_support_iff.mp ha, AddMonoidAlgebra.single_zero]
    exact I.zero_mem

/-- Characterization of membership in a monomial ideal. -/
lemma Ideal.IsMonomial.mem_iff {I : Ideal (AddMonoidAlgebra R A)} (hI : I.IsMonomial)
    {f : AddMonoidAlgebra R A} :
    f ∈ I ↔ ∀ a ∈ f.coeff.support, AddMonoidAlgebra.single a (f.coeff a) ∈ I := by
  constructor
  · exact fun hf a _ => hI.single_mem hf a
  · intro h
    rw [← AddMonoidAlgebra.sum_coeff_single f]
    exact I.sum_mem fun a ha => h a ha

/- Over a semifield, monomial ideals are characterized as those containing
each term of their elements. -/
lemma Ideal.isMonomial_iff_single_mem [Semifield k]
    (I : Ideal (AddMonoidAlgebra k A)) :
    I.IsMonomial ↔ ∀ f ∈ I, ∀ a, AddMonoidAlgebra.single a (f.coeff a) ∈ I :=
  Iff.intro (fun hI f hf a => hI.single_mem hf a) (fun hI f hf a ha =>
    (AddMonoidAlgebra.single_mem_iff_of_isUnit I a (by simpa using ha)).mp (hI f hf a))

@[simp]
lemma Ideal.IsMonomial.bot : IsMonomial (⊥ : Ideal (AddMonoidAlgebra R A)) := by
  rw [Ideal.IsMonomial.iff_exists]
  exact ⟨∅, by simp⟩

@[simp]
lemma Ideal.IsMonomial.top : IsMonomial (⊤ : Ideal (AddMonoidAlgebra R A)) := by
  simp [IsMonomial]

end
